name: Sync LICENSE.md from ./* to <platform>/*, then ./* to adamlui/chatgpt-apps/chatgpt-infinity/*, then greasemonkey/* to adamlui/userscripts/chatgpt/chatgpt-infinity/*

on:
  push:
    branches: main
    paths:
      - "*"
      - "docs/**"
      - "media/**"

jobs:
  build:
    if: (github.repository == 'adamlui/chatgpt-infinity') && (github.event.commits[0].committer.username != 'kudo-sync-bot')
    runs-on: ubuntu-latest
    steps:

      - name: Checkout adamlui/chatgpt-infinity
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-infinity
          path: adamlui/chatgpt-infinity
          fetch-depth: 2

      - name: Checkout adamlui/chatgpt-apps
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-apps
          path: adamlui/chatgpt-apps

      - name: Checkout adamlui/userscripts
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/userscripts
          path: adamlui/userscripts

      - name: Sync LICENSE.md from ./* to <platform>/*
        run: |
          cd ${{ github.workspace }}/adamlui/chatgpt-infinity
          platforms=($(find . -type d -name "docs" | # paths to docs/
            awk -F'/' '{print $(NF-1)}' | # filter to parents
            grep -v "^.$")) # exclude root
          echo "Platforms: ${platforms[@]}"
          languages=($(ls docs/*/LICENSE.md | # paths to LICENSEs
            awk -F'/' '{print $(NF-1)}') # filter to parents
            "en") # include English
          echo -e "Languages: ${languages[@]}\n"
          for lang in "${languages[@]}"; do
            root_license=$([[ "$lang" != "en" ]] && echo "docs/$lang" || echo ".")/LICENSE.md
            root_license_content=$(git show HEAD:"$root_license")
            root_license_modified=$(git log -1 --format="%ct" -- "$root_license")
            for platform in "${platforms[@]}"; do
              platform_license=$platform/$([[ "$lang" != "en" ]] && echo "docs/$lang/" || echo "")LICENSE.md
              platform_license_content=$(git show HEAD:"$platform_license")
              platform_license_modified=$(git log -1 --format="%ct" -- "$platform_license")
              if [[ $root_license_modified -gt $platform_license_modified ]] ; then
                if [[ "$root_license_content" != "$platform_license_content" ]] ; then
                  cp -f "$root_license" "$platform_license"
                  echo "Copied $root_license to $platform_license"
          fi ; fi ; done; done

      - name: Sync ./* to adamlui/chatgpt-apps/chatgpt-infinity/*
        run: |
          rsync -avhr --delete --exclude={'.*','package*json'} \
            ${{ github.workspace }}/adamlui/chatgpt-infinity/ \
            ${{ github.workspace }}/adamlui/chatgpt-apps/chatgpt-infinity/

      - name: Sync greasemonkey/* to adamlui/userscripts/chatgpt/chatgpt-infinity/*
        run: |
          rsync -avhr --delete \
            ${{ github.workspace }}/adamlui/chatgpt-infinity/greasemonkey/ \
            ${{ github.workspace }}/adamlui/userscripts/chatgpt/chatgpt-infinity/

      - name: Push to adamlui/chatgpt-infinity
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: --force
          add_options: --all
          commit_user_email: auto-sync@kudoai.com
          commit_message: "${{ github.event.head_commit.message }} ↞ [auto-sync from `root`]"
          file_pattern: "**"
          repository: adamlui/chatgpt-infinity

      - name: Push to adamlui/chatgpt-apps
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: --force
          add_options: --all
          commit_user_email: auto-sync@kudoai.com
          commit_message: "${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/chatgpt-infinity`]"
          file_pattern: "chatgpt-infinity/**"
          repository: adamlui/chatgpt-apps

      - name: Push to adamlui/userscripts
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: --force
          add_options: --all
          commit_user_email: auto-sync@kudoai.com
          commit_message: "${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/chatgpt-infinity`]"
          file_pattern: "chatgpt/chatgpt-infinity/**"
          repository: adamlui/userscripts
