name: Publish to AMO on FF version bump

on:
  push:
    branches: [main]
    paths: [firefox/extension/manifest.json]

jobs:
  check-version-to-publish:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout adamlui/chatgpt-infinity
        uses: actions/checkout@v4
        with:
          sparse-checkout: firefox
          fetch-depth: 2

      - name: Check FF manifest for version bump
        run: |
          CURRENT_VER=$(cat firefox/extension/manifest.json | grep '"version"' | sed -E 's/.*"version": "(.*)".*/\1/')
          PREV_VER=$(git show HEAD^:firefox/extension/manifest.json | grep '"version"' | sed -E 's/.*"version": "(.*)".*/\1/')
          if [ "$(printf '%s\n' "$PREV_VER" "$CURRENT_VER" | sort -V | head -n 1)" != "$CURRENT_VER" ] ; then
               echo "Extension updated from $PREV_VER to $CURRENT_VER"
               echo "VERSION_CHANGED=true" >> $GITHUB_ENV
          else echo "VERSION_CHANGED=false" >> $GITHUB_ENV ; fi

      - name: Create zipball
        if: env.VERSION_CHANGED == 'true'
        run: |
          cd firefox/extension
          zip -r ../../extension.zip .

      - name: Publish to AMO
        if: env.VERSION_CHANGED == 'true'
        uses: cardinalby/webext-buildtools-firefox-addons-action@v1
        with:
          zipFilePath: 'extension.zip'
          extensionId: 'chatgpt.infinity@chatgptevo.com'
          jwtIssuer: ${{ secrets.AMO_ISSUER }}
          jwtSecret: ${{ secrets.AMO_SECRET }}
