name: Publish to CWS on Chrome version bump

on:
  push:
    branches: [main]
    paths: [chrome/extension/manifest.json]

jobs:
  check-version-to-publish:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout adamlui/chatgpt-infinity
        uses: actions/checkout@v4
        with:
          sparse-checkout: chrome
          fetch-depth: 2

      - name: Check Chrome manifest for version bump
        run: |
          CURRENT_VER=$(cat chrome/extension/manifest.json | grep '"version"' | sed -E 's/.*"version": "(.*)".*/\1/')
          PREV_VER=$(git show HEAD^:chrome/extension/manifest.json | grep '"version"' | sed -E 's/.*"version": "(.*)".*/\1/')
          if [ "$(printf '%s\n' "$PREV_VER" "$CURRENT_VER" | sort -V | head -n 1)" != "$CURRENT_VER" ] ; then
               echo "Extension updated from $PREV_VER to $CURRENT_VER"
               echo "version_changed=true" >> $GITHUB_ENV
          else echo "version_changed=false" >> $GITHUB_ENV ; fi

      - name: Create zipball
        if: env.version_changed == 'true'
        run: |
          cd firefox/extension
          zip -r ../../extension.zip .

      - name: Publish to CWS
        if: env.version_changed == 'true'
        uses: trmcnvn/chrome-addon@v2
        with:
          extension: amikeononomkhphopbflomhnmdijjpmb
          zip: extension.zip
          client-id: ${{ secrets.CWS_CLIENT_ID }}
          client-secret: ${{ secrets.CWS_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CWS_REFRESH_TOKEN }}
