name: Publish to AMO on FF version bump

on:
  push:
    branches: [main]
    paths: [firefox/extension/manifest.json]

jobs:
  check-version-to-publish:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout adamlui/chatgpt-infinity
        uses: actions/checkout@v4
        with:
          sparse-checkout: firefox
          fetch-depth: 2

      - name: Check FF manifest for version bump
        run: |
          CURRENT_VER=$(cat firefox/extension/manifest.json | grep '"version"' | sed -E 's/.*"version": "(.*)".*/\1/')
          PREV_VER=$(git show HEAD^:firefox/extension/manifest.json | grep '"version"' | sed -E 's/.*"version": "(.*)".*/\1/')
          if [ "$(printf '%s\n' "$PREV_VER" "$CURRENT_VER" | sort -V | head -n 1)" != "$CURRENT_VER" ] ; then
               echo "Extension updated from $PREV_VER to $CURRENT_VER"
               echo "version_changed=true" >> $GITHUB_ENV
          else echo "version_changed=false" >> $GITHUB_ENV ; fi

      - name: Create zipball
        if: env.version_changed == 'true'
        run: zip -r extension.zip firefox/extension

      - name: Publish to AMO
        if: env.version_changed == 'true'
        uses: yayuyokitano/firefox-addon@v0.0.6-alpha
        with:
          api_key: ${{ secrets.AMO_ISSUER }}
          api_secret: ${{ secrets.AMO_SECRET }}
          guid: "chatgpt.infinity@chatgptevo.com"
          xpi_path: extension.zip
