name: Sync firefox/extension/_locales/* to chrome/extension/_locales/*, then * to adamlui/chatgpt-apps/chatgpt-infinity/*

on:
  push:
    branches: [main]
    paths: [firefox/**]

jobs:
  build:
    if: (github.repository == 'adamlui/chatgpt-infinity') && (github.event.commits[0].committer.username != 'kudo-sync-bot')
    runs-on: ubuntu-latest
    env:
      GIT_AUTHOR_NAME: ${{ github.event.commits[0].author.name }}
      GIT_AUTHOR_EMAIL: ${{ github.event.commits[0].author.email }}
      GIT_COMMITTER_NAME: kudo-sync-bot
      GIT_COMMITTER_EMAIL: auto-sync@kudoai.com

    steps:

      - name: Checkout adamlui/chatgpt-infinity
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-infinity
          path: adamlui/chatgpt-infinity
          fetch-depth: 2

      - name: Checkout adamlui/chatgpt-apps
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-apps
          path: adamlui/chatgpt-apps

      - name: Sync firefox/extension/_locales/* to chrome/_locales/*
        run: |
          rsync -avhr --delete \
            "${{ github.workspace }}/adamlui/chatgpt-infinity/firefox/extension/_locales/" \
            "${{ github.workspace }}/adamlui/chatgpt-infinity/chrome/extension/_locales"

      - name: Sync * to adamlui/chatgpt-apps/chatgpt-infinity/*
        run: |
          rsync -avhr --delete --exclude={'.*','eslint*','package*json'} \
            ${{ github.workspace }}/adamlui/chatgpt-infinity/ \
            ${{ github.workspace }}/adamlui/chatgpt-apps/chatgpt-infinity/

      - name: Escape backticks in commit msg
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: |
          echo "ESCAPED_MSG<<EOF" >> $GITHUB_ENV
          echo "$COMMIT_MSG" | sed 's/`/\`/g' >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Push changes to adamlui/chatgpt-infinity
        run: |
          cd ${{ github.workspace }}/adamlui/chatgpt-infinity
          git add .
          git commit -n -m "$ESCAPED_MSG ↞ [auto-sync from \`firefox\`]" || true
          git push

      - name: Push changes to adamlui/chatgpt-apps
        run: |
          cd ${{ github.workspace }}/adamlui/chatgpt-apps
          git add .
          git commit -n -m "$ESCAPED_MSG ↞ [auto-sync from \`adamlui/chatgpt-infinity/firefox\`]" || true
          git push
